// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetLoginServers() {
  return window['go']['main']['App']['GetLoginServers']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function StartCaptureCharacterServerList(arg1) {
  return window['go']['main']['App']['StartCaptureCharacterServerList'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
