// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetLoginServers():Promise<Array<config.LoginServer>>;

export function Greet(arg1:string):Promise<string>;

export function StartCaptureCharacterServerList(arg1:string):Promise<void>;
