// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetLoginServers() {
  return window['go']['main']['App']['GetLoginServers']();
}

export function OpenAuthorPage() {
  return window['go']['main']['App']['OpenAuthorPage']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
