// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {ragnarok} from '../models';

export function CheckForUpdate():Promise<string>;

export function GetLoginServers():Promise<Array<config.LoginServer>>;

export function OpenGitHub():Promise<void>;

export function StartCapture(arg1:string):Promise<Array<ragnarok.CharacterServerInfo>>;

export function StopCapture():Promise<boolean>;
